#!/usr/bin/env bash

function msg {
    echo -e "$1" 1>&2
}

msg "Looking for .cabal files in '$1'"

shopt -s nullglob
for CBL in "$1"/*.cabal
do
    msg "Found '$CBL' in '$1'"
    NAME=$(grep -i "name[ ]*:" < "$CBL" | cut -d ':' -f 2 | tr -d '[:space:]')
    msg "Project name is '$NAME'"
    echo "$NAME"
    exit 0
done

msg "Couldn't find name of package in '$1'"
exit 1
