#!/usr/bin/env bash
set -e

command -v jq > /dev/null || {
    echo "dump-package requires jq, aborting" >> /dev/stderr
    exit 1
}

BASE=$(dirname "$(readlink -f "$0")")

for CMD in runAstPlugin dump-package-env dump-format dump-package-name
do
    [[ -e "$BASE/$CMD" ]] || {
        echo "Didn't find $CMD in '$BASE'" >> /dev/stderr
        exit 1
    }
done

# Extract ASTs from a Cabal package

function runPlugin {
    ENV=$("$BASE/dump-package-env" "$DIR") || {
        echo "Unable to get package environment; aborting" >> /dev/stderr
        exit 1
    }
    nix-shell --show-trace \
              -E "$ENV" \
              --run "'$BASE/runAstPlugin' '$DIR'"
}

[[ "$#" -eq 0 ]] && echo "Please specify a Cabal project directory" && exit 1

DIR="$1"

runPlugin
