#!/usr/bin/env bash

[[ "$#" -lt 1 ]] && {
    echo "dump-package-env needs a Cabal project directory" >> /dev/stderr
    exit 1
}

[[ -d "$1" ]] || {
    echo "Directory '$1' not found" >> /dev/stderr
    exit 1
}

DIR="$1"
BASE=$(dirname "$(readlink -f "$0")")
PKG=$("$BASE/dump-package-name" "$DIR")

if [[ -e "$BASE/ghcWithPlugin.nix" ]]
then
    GHCWITHPLUGIN="$BASE/ghcWithPlugin.nix"
elif [[ -e "$BASE/../lib/ghcWithPlugin.nix" ]]
then
    GHCWITHPLUGIN="$BASE/../lib/ghcWithPlugin.nix"
else
    echo "Didn't find ghcWithPlugin.nix in '$BASE' or '$BASE/../lib'" >> /dev/stderr
    exit 1
fi

echo "with import <nixpkgs> {}; import \"$GHCWITHPLUGIN\" \"$PKG\""
