#!/usr/bin/env bash

function msg {
    echo -e "$1" 1>&2
}

[[ "$#" -lt 1 ]] && {
    msg "dump-package-env needs a Cabal project directory"
    exit 1
}

[[ -d "$1" ]] || {
    msg "Directory '$1' not found"
    exit 1
}

DIR="$1"
BASE=$(dirname "$(readlink -f "$0")")
PKG=$("$BASE/dump-package-name" "$DIR")

if [[ -e "$BASE/ghcWithPlugin.nix" ]]
then
    GHCWITHPLUGIN="$BASE/ghcWithPlugin.nix"
elif [[ -e "$BASE/../lib/ghcWithPlugin.nix" ]]
then
    GHCWITHPLUGIN="$BASE/../lib/ghcWithPlugin.nix"
else
    msg "Didn't find ghcWithPlugin.nix in '$BASE' or '$BASE/../lib'"
    exit 1
fi

echo "with import <nixpkgs> {}; import \"$GHCWITHPLUGIN\" \"$PKG\""
