#!/usr/bin/env bash
set -e

DIR=$(mktemp -d)
BASE=$(dirname "$0")

[[ -e "$BASE/dump-package" ]] || {
    echo "Did not find dump-package in '$BASE'" >> /dev/stderr
    exit 1
}

(cd "$DIR";
 for PKG in "$@"
 do
     nix-shell --show-trace \
               -p haskellPackages.cabal-install \
               --run "cabal update; cabal get $PKG" >> /dev/stderr
 done)

(shopt -s nullglob
 for PROJECT in "$DIR"/*
 do
     echo "Dumping package $PROJECT" >> /dev/stderr
     "$BASE/dump-package" "$PROJECT"
 done)

rm -rf "$DIR"
