#!/usr/bin/env bash

STDIN=0

if [[ "$#" -gt 0 ]]
then
    echo "Reading clusters from '$1'" >> /dev/stderr
    INPUT=$(cat "$1")
elif ! [ -t 0 ]
then
    echo "Reading clusters from stdin" >> /dev/stderr
    STDIN=1
    INPUT=$(cat)
else
    echo "Error: Please supply a filename or input to stdin" >> /dev/stderr
    exit 1
fi

function explore {
    PKGS=$(echo "$INPUT" | getPkgs)
    nix-shell --run "MLSpec $*" -p $PKGS
}

function getPkgs {
    # Packages required for MLSpec
    for PKG in mlspec mlspec-helper runtime-arbitrary
    do
        printf "haskellPackages.$PKG"
    done

    # Haskell packages taken from JSON
    jq -r '.[] | .[] | .package'       | # Extract packages as unquoted strings
        sort -u                        | # Remove dupes
        sed -e 's/^/haskellPackages./' | # Prefix with "haskellPackages."
        tr '\n' ' '                      # Join package names with spaces

    echo "" # For the newline
}

if [[ "$STDIN" -eq 1 ]]
then
    echo "$INPUT" | explore "$@"
else
    explore "$@"
fi
