#!/bin/sh

# Extract ASTs from Haskell projects

test "$#" -lt 1 && echo "Please provide a destination" && exit 1

function abs_dir {
    (cd "$1" &>/dev/null && printf "%s" "$PWD")
}

DEST=$(abs_dir $1)

echo "Writing to $1 ($DEST)"

test ! -d "$DEST" && echo "Dest must be a directory ($DEST)" && exit 1

find . -iname "*.hs" -o -iname "*.lhs" | while read LINE
                                         do
                                             echo "Scanning $LINE into $DEST"
                                             echo "$LINE" | HS2AST "$DEST"
                                         done
