#!/bin/sh

# Perform feature extraction on ASTs from HS2AST

test "$#" -lt 2 && echo "Please provide a source and a destination" && exit 1

function is_dir {
    test ! -d "$2" && echo "$1 must be a directory" && exit 1
}

function abs_dir {
    (cd "$1" &>/dev/null && printf "%s" "$PWD")
}

SOURCE=$(abs_dir "$1")
DEST=$(abs_dir "$2")

is_dir("Source"       "$SOURCE")
is_dir("Destination", "$DEST")

echo "Extracting from $SOURCE to $DEST"

shopt -s nullglob
for PKG2 in "$SOURCE/"*
do
    PKG=$(basename "$PKG2")
    echo "Found package $PKG"
    mkdir -p "$DEST/$PKG"
    for MOD2 in "$SOURCE/$PKG/"*
    do
        MOD=$(basename "$MOD2")
        echo "Found module $MOD"
        mkdir -p "$DEST/$PKG/$MOD"
        for NAME2 in "$SOURCE/$PKG/$MOD/"*
        do
            NAME=$(basename "$NAME2")
            echo "Found name $NAME"
            MODE=sexpr BITS=30 TreeFeatures < "$SOURCE/$PKG/$MOD/$NAME" > "$DEST/$PKG/$MOD/$NAME"
        done
    done
done
