#!/usr/bin/env bash

for CMD in jq GetDeps rev
do
    command -v "$CMD" > /dev/null || {
        echo "ERROR: getDeps needs '$CMD'" >> /dev/stderr
        exit 1
    }
done

jq -c '.[]' | while read -r LINE
do
    DEPENDENCIES=$(echo "$LINE" | jq -r '.ast' | GetDeps)
    [[ -z "$DEPENDENCIES" ]] && echo "Unexpected line: $LINE" >> /dev/stderr

    # Split versions from the package names
    VERSIONED=$(echo "$DEPENDENCIES" | jq -c '.[]' | while read -r DEP
    do
        PKG=$(echo "$DEP" | jq -cr '.package')
        if echo "$PKG" | grep -- "-[0-9][0-9.]*$" > /dev/null
        then
            # We have a version number in our package field; split it up
            NAME=$(echo    "$PKG" | rev | cut -d '-' -f 2- | rev)
            VERSION=$(echo "$PKG" | rev | cut -d '-' -f 1  | rev)

            # shellcheck disable=SC2016
            echo "$DEP" | jq --arg name "$NAME"       \
                             --arg version "$VERSION" \
                             '. + {"package":$name,"version":$version}'
        else
            # We don't have a version number in our package field; leave as-is
            echo "$DEP"
        fi
    done | jq -s '.')

    # Add the dependencies to the object
    echo "$LINE" | jq -c ". + {\"dependencies\": $VERSIONED }"
done  | jq -s '.'
