#!/usr/bin/env bash

for CMD in jq GetDeps
do
    command -v "$CMD" > /dev/null || {
        echo "ERROR: getDeps needs '$CMD'" >> /dev/stderr
        exit 1
    }
done

jq -c '.[]' | while read -r LINE
do
    DEPENDENCIES=$(echo "$LINE" | jq -r '.ast' | GetDeps )
    [[ -z "$DEPENDENCIES" ]] && echo "LINE: $LINE" >> /dev/stderr

    # Add the dependencies to the object
    echo "$LINE" | jq -c ". + {\"dependencies\": $DEPENDENCIES }"
done  | jq -s '.'
