#!/usr/bin/env bash

# Runs AstPlugin.
#
# This script makes the following assumptions:
#  - The path to a Cabal project is given as an argument
#  - All of the project's dependencies are in the database of ghc-pkg
#  - AstPlugin is also in the database of ghc-pkg

# The dependency requirements can be satisfied by running in nix-shell

set -e

function getAsts {
    RESULT=$(build)
    { echo "$RESULT" | grep -v "^{" >> /dev/stderr; } || true
      echo "$RESULT" | grep    "^{"
}

function build {
    # Override pkg db to get project's dependencies and AstPlugin
    GHC_PKG=$(ghc-pkg list | head -n 1 | tr -d ':')
    OPTIONS="-package-db=$GHC_PKG -package AstPlugin -fplugin=AstPlugin.Plugin"
    # NOTE: We swap stderr (2) and stdout (1) via a temporary fd (3), since GHC
    # plugins write to stderr
    cabal --ghc-options="$OPTIONS" build 3>&2 2>&1 1>&3
}

[[ "$#" -eq 0 ]] && echo "runAstPlugin needs a directory" && exit 1

cd "$1"
cabal configure >> /dev/stderr
getAsts
