{ cabal-install, drvFromScript }:
with builtins;

pkgName:
assert isString pkgName;

# Try to download the given package from Hackage and add it to the Nix store.
# Since everything in $out will inherit all of this script's dependencies, the
# only thing we put in there is a path generated by 'nix-store --add', which
# depends only on the content of the Haskell package.

drvFromScript { inherit pkgName; buildInputs = [ cabal-install ]; } ''
  set -e
  mkdir pkg
  cd pkg

  export HOME="$TMPDIR"
  cabal update
  cabal get "$pkgName" || exit 1
  for D in ./*
  # */
  do
    cp -ar "$D" "$out"
    break
  done
''
