#!/usr/bin/env bash
BASE=$(dirname "$(dirname "$(readlink -f "$0")")")

# shellcheck source=common.sh
source "$BASE/scripts/common.sh"

# Forget all failures, so we retry every package on the next benchmarking run

for F in unquickspecable unexplorable unfetchable unclusterable unbuildable \
         featureless finished
do
    echo "" > "$CACHE/$F"
done
