#!/usr/bin/env bash
set -e

function msg {
    echo -e "$1" 1>&2
}

command -v jq > /dev/null || {
    msg "dump-package requires jq, aborting"
    exit 1
}

BASE=$(dirname "$(readlink -f "$0")")

for CMD in runAstPlugin dump-package-env dump-format dump-package-name
do
    [[ -e "$BASE/$CMD" ]] || {
        msg "Didn't find $CMD in '$BASE'"
        exit 1
    }
done

# Extract ASTs from a Cabal package

function runPlugin {
    ENV=$("$BASE/dump-package-env" "$DIR") || {
        msg "Unable to get package environment; aborting"
        exit 1
    }
    nix-shell --show-trace \
              -E "$ENV" \
              --run "'$BASE/runAstPlugin' '$DIR'"
}

[[ -n "$DIR" ]] || DIR="$1"
[[ -n "$DIR" ]] || {
    msg "Please provide a package directory, either as argument or DIR"
    exit 1
}

runPlugin
