#!/usr/bin/env bash

BASE=$(dirname "$(readlink -f "$0")")
PKG=$("$BASE/dump-package-name" "$1")

# Set NOFORMAT to avoid calling jq, eg. for testing
if [[ -z $NOFORMAT ]]
then
    jq -c ". + {package: \"$PKG\"}" | jq -s '.'
else
    cat
fi
